### ISSUE TITLE
client.splits.list doesn't work anymore

### ISSUE THREAD

**Issue by SerhiiKorolik** [splitio/python-api#14] opened 2023-08-21 11:15 UTC
Code:

```
from splitapiclient.main import get_client

client = get_client({"apikey": 'MY_TOKEN'})

for split in client.splits.list("MY_WS_ID"):
    print ("\nSplit: "+split.name+", "+split._workspace_id)
```

Returns:
```
Traceback (most recent call last):
  File "/Users/user/Documents/split.py", line 5, in <module>
    for split in client.splits.list("SECRET_OUTPUT"):
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/splitapiclient/microclients/split_microclient.py", line 122, in list
    response = self._http_client.make_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/splitapiclient/http_clients/sync_client.py", line 114, in make_request
    self._handle_invalid_response(response)
  File "/opt/homebrew/lib/python3.11/site-packages/splitapiclient/http_clients/sync_client.py", line 56, in _handle_invalid_response
    raise exc()
splitapiclient.util.exceptions.HTTPNotFoundError: None
    
```

**Comment by SerhiiKorolik** [comment] 2023-08-21 11:32
Can be related? 
https://github.com/splitio/python-api/blob/master/splitapiclient/http_clients/sync_client.py#L58
Also don't see splits [here](https://docs.split.io/reference/introduction) anymore, instead I see [feature flags](https://docs.split.io/reference/feature-flag).

**Comment by SerhiiKorolik** [comment] 2023-08-21 14:18
Alright, I was able to use` client.split_definitions.list()` instead of `client.splits.list()` but still, the issue is persist. And I can't add split to environment (e.g. `split.add_to_environment()` ) because in order to have the split object I need to run `client.splits.find()` which is also doesn't work

**Comment by SerhiiKorolik** [comment] 2023-08-22 13:13
@kleinjoshuaa would be nice if you could take a look 🙏

**Comment by SerhiiKorolik** [comment] 2023-08-28 10:05
Not sure what it was, but now it works. Still will keep the issue open, just to make sure proper message appears in errors. Not just `HTTPNotFoundError: None`

**Comment by kleinjoshuaa** [comment] 2023-09-07 20:37
Hi @SerhiiKorolik this was actually due to a regression with the Admin API backend that has been resolved.

**Comment by kleinjoshuaa** [comment] 2023-09-07 20:44
This issue with `None` being the message returned from an HTTP error will be resolved in the next release

**Closed by kleinjoshuaa** 2023-09-07 20:44 UTC

**Comment by SerhiiKorolik** [comment] 2023-09-07 20:46
Nice. Appreciated

**Comment by SerhiiKorolik** [comment] 2023-12-04 13:06
Looks like the issue is back again
```
Traceback (most recent call last):
  File "/Users/me/Documents/GitHub/test/split/split.py", line 32, in <module>
    for split in client.splits.list(ws.id):
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/me/.pyenv/versions/3.12.0/lib/python3.12/site-packages/splitapiclient/microclients/split_microclient.py", line 122, in list
    response = self._http_client.make_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/me/.pyenv/versions/3.12.0/lib/python3.12/site-packages/splitapiclient/http_clients/sync_client.py", line 114, in make_request
    self._handle_invalid_response(response)
  File "/Users/me/.pyenv/versions/3.12.0/lib/python3.12/site-packages/splitapiclient/http_clients/sync_client.py", line 56, in _handle_invalid_response
    raise exc(response.text)
splitapiclient.util.exceptions.HTTPNotFoundError: {"code":404,"message":"","details":"","transactionId":"ID_IS_HERE"}
```

cc: @kleinjoshuaa

**Comment by SerhiiKorolik** [comment] 2023-12-07 18:31
Yes. Same.

the version is:
```
$ pip3 install splitapiclient
Requirement already satisfied: splitapiclient in /Users/me/.pyenv/versions/3.12.0/lib/python3.12/site-packages (3.1.9)
```

Maybe anything else I can check for my side?
Some versions, or some specific api calls?

**Comment by SerhiiKorolik** [comment] 2023-12-07 18:34
Actually, upgraded to the latest (3.1.10) and the issue is still here..
@kleinjoshuaa

**Comment by kleinjoshuaa** [comment] 2023-12-07 18:35
@SerhiiKorolik 

Can you try enabling logging in python - do you only just get a 404 error? What if you try using `CURL` to list the feature flags using this endpoint do you get the same error? 

https://docs.split.io/reference/list-feature-flags <- the wrapper uses this endpoint. Can you try to list feature flags and see if that works with your API key?

**Comment by SerhiiKorolik** [comment] 2023-12-07 18:49
@kleinjoshuaa 

When I entered the wrong ws_id I got this reply:

`{"code":404,"message":"Resource not found"}`

But when I entered the correct one from the url of the actual site, I got:

`{"code":404,"message":"","details":"","transactionId":"SOME_ID_IS_HERE"}`

Not sure if the ID in the response can be public, so put SOME_ID_IS_HERE instead

**Comment by kleinjoshuaa** [comment] 2023-12-07 18:51
Thanks @SerhiiKorolik  - I think you should file a support ticket (email support@split.io) with your curl command - this may be an issue with the backend or possibly your api key

**Comment by SerhiiKorolik** [comment] 2023-12-07 18:52
Thank you
